layout: sidebar
style: light

port: 4040

plugins:
  - jekyll-octicons
  - jekyll-github-metadata
  - jekyll-seo-tag
  - jekyll-sitemap
  - jemoji

permalink: :title/

defaults:
  - scope:
      path: "" # an empty string here means all files in the project
      type: "posts"
    values:
      layout: "post"

projects:
  sort_by: stars
  limit: 36
  exclude:
    archived: true
    forks: true
    projects:
      - old-projects
      - old-blog
      - brennanbrown
      - fyyur
      - eleventy-sandbox
      - brennanbrown.github.io
      - js
      - hugo-cms-test
      - dotfiles
      - med11
      - med12
      - stars
      - offline
      - kindreadthepoet
      - site
      - communityandromance
      - plainjournal
      - sakura
      - eleventy-sandbox

# topics:
#   - name: CSS
#     web_url: https://github.com/topics/css
#     image_url: https://raw.githubusercontent.com/github/explore/6c6508f34230f0ac0d49e847a326429eefbfc030/topics/css/css.png

#   - name: Web design

#   - name: Sass
#     web_url: https://github.com/topics/sass
#     image_url: https://raw.githubusercontent.com/github/explore/6c6508f34230f0ac0d49e847a326429eefbfc030/topics/sass/sass.png
